version: '3.8'
services:
  product-service:
    build: .
    container_name: product-service

    environment:
      RABBITMQ_URL:  "amqp://guest:guest@rabbitmq:5672/"
      PROM_URL:       "http://prometheus:9090"
      GRAFANA_URL:    "http://grafana:3000"
    ports:
      - "8002:8002"
    networks:
      - app-network

networks:
  app-network:
    external: true
